config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'

  get 'posts/create'

  get 'posts/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root 'posts#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  resources :posts, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :posts
  before_create :create_token_for_user
  before_save {self.email = email.downcase}
  validates :username, presence: true, length: {maximum: 50},
  uniqueness: {case_sensitive:false}

  validates :password, presence: true, length: {minimum: 8}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
  format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}

  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def create_token_for_user
    self.remember_token = User.digest(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :need_to_login, only: [:new, :create]
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(user_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def index
    @posts = Post.all
  end

  private

    def user_params
      params.require(:post).permit(:content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      #log user in
      log_in(user)
      redirect_to root_path
    else
      #error message
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "You're signed up #{@user.username}!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :username, :password)
  end

  def require_logged_out
    if logged_in?
      flash.now[:error] = "Please logout if you wish to sign up a new user"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    the_remember_token = user.remember_token
    cookies.permanent[:the_remember_token] = the_remember_token
    user.update_attribute(:remember_token, User.digest(the_remember_token))
    self.current_user = user
  end

  def current_user
    the_remember_token = User.digest(cookies[:the_remember_token])
    user = @current_user ||= User.find_by(remember_token: the_remember_token)
    return nil unless user
    user
  end

  def current_user=(user)
    @current_user = user
  end

  def log_out
    current_user.update_attribute(:remember_token, current_user.create_token_for_user)

    cookies.delete(:the_remember_token)
    self.current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def need_to_login
    unless logged_in?
      flash[:error] = "Please log in"
      redirect_to root_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap core CSS -->
  <link href="https://blackrockdigital.github.io/startbootstrap-clean-blog/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="https://blackrockdigital.github.io/startbootstrap-clean-blog/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="https://blackrockdigital.github.io/startbootstrap-clean-blog/css/clean-blog.min.css" rel="stylesheet">
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand"><%= link_to "See the code", "https://github.com/IvyMic/members-only"%></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <% if logged_in? %>
              <li class="nav-item nav-link">
                <%= link_to "Log out", logout_path%>
              </li>
              <li class="nav-item nav-link">
                <%= link_to "Spread the word", posts_new_path%>
              </li>
            <% else %>
            <li class="nav-item nav-link">
              <%= link_to "Log in", login_path %>
            </li>
            <li class="nav-item nav-link">
              <%= link_to "Sign up", new_user_path %>
            </li>
            <% end %>
            <li class="nav-item nav-link">
              <%= link_to "Home", root_path%>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url('https://blackrockdigital.github.io/startbootstrap-clean-blog/img/home-bg.jpg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>Gossip App</h1>
              <span class="subheading">Make a post that will be seen by everyone, but only signed up users can see who said what</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <% flash.each do |message_type, message| %>
            <div id="flash" class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>





    <!-- Bootstrap core JavaScript -->
    <script src="https://blackrockdigital.github.io/startbootstrap-clean-blog/vendor/jquery/jquery.min.js"></script>
    <script src="https://blackrockdigital.github.io/startbootstrap-clean-blog/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="https://blackrockdigital.github.io/startbootstrap-clean-blog/js/clean-blog.min.js"></script>

  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <% if logged_in? %>
    <% author = post.user.username %>
  <% else %>
    <% author = "Anonymous" %>
  <% end %>
  <div class="post-preview">
    <h3 class="post-subtitle">
      <%= post.content %>
    </h3>
    <p class="post-meta"> Posted by <%= author %> </p>
    <hr>
  </div>
<% end %>
<!-- Pager -->
<div class="clearfix">
  <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
</div>

app/views/posts/new.html.erb
<% provide(:title, "New Post") %>

<div class="form-login">
	<h1>Spread the word!</h1>
	<%= form_for(:post, url: posts_path) do |f| %>
		<%= f.text_area :content, class: "form-control input-lg chat-input"%><br>
		<%= f.submit "Post", class: "btn btn-primary btn-md" %>
	<% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, "New User") %>

<div class="container" id="login_container">
  <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="form-login">
					<h1>New User</h1>
					<%= form_for(:user, url: users_path) do |f| %>
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control input-lg chat-input"%><br>

						<%= f.label :username %>
						<%= f.text_field :username, class: "form-control input-lg chat-input"%><br>

            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control input-lg chat-input"%><br>

						<%= f.submit "Submit", class: "btn btn-primary btn-md" %>
					<% end %>
        </div>
      </div>
    </div>
</div>